 kumuluzee:
   name: cxf-sample
   env:
     name: dev
   version: 1.0.0
   server:
     http:
       port: 4444
   jax-ws:
    - path: /soap
      implementation-class: com.kumuluz.ee.cxf.sample.CalculatorSoapServiceBean
      wsdl-location: /webapp/WEB-INF/wsdls/calculatorSample.wsdl