 kumuluzee:
   name: cxf-sample
   env:
     name: dev
   version: 1.0.0
   server:
     http:
       port: 4444
   jax-ws:
    - web-context: /soap
      url: /calculator
      implementation-class: com.kumuluz.ee.cxf.sample.CalculatorSoapServiceBean
    - web-context: /soap
      url: /calc2
      implementation-class: com.kumuluz.ee.cxf.sample.CalculatorSoapServiceBean