 kumuluzee:
   name: cxf-sample
   env:
     name: dev
   version: 1.0.0
   server:
     http:
       port: 4444
   datasources:
      - jndi-name: jdbc/CustomersDS
        connection-url: jdbc:postgresql://localhost:5432/customers
        username: postgres
        password: postgres
        max-pool-size: 20